Populate main package vignette
neurogenomics/MotifStats pull request #2
Opened 2024-04-17 10:45 UTC by HDash

Initial draft - Issue #1

2024-04-17 11:06 UTC, HDash commented
rworkflows checks failing for unrelated reasons.  

Error:  

```
remote: Permission to neurogenomics/MotifStats.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/neurogenomics/MotifStats.git/': The requested URL returned error: 403
```

2024-04-18 08:26 UTC, Tomrrr1 requested changes

2024-04-18 16:21 UTC, HDash reviewed
Correct typos and improved documentation. Additionally, change the `run_Ame` output directory behaviour to follow the roxygen `out_dir` parameter documentation.

2024-04-19 09:48 UTC, Tomrrr1 approved these changes

2024-04-19 09:48 UTC, Tomrrr1 commented on R/peak_proportion.R
Good spot

2024-04-19 09:48 UTC, merged